spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board2023
    username: root
    password: green502
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false  # default : true인데 false로 바꾸는게 불문율
    hibernate:
      ddl-auto: create # create로 설정하면 서버가 실행될 때마다 테이블을 새로 생성함
    properties:
      hibernate:
        format_sql: true # sql을 보기 좋게 출력
        show_sql: true # 콘솔창에 sql이 보이게 함
    generate-ddl: true # DDL을 자동으로 생성


file:
  dir: /home/download/

springdoc:
  swagger-ui:
    path: /swagger.html